apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Z5tP9x/zZ0j9iWHOsw==,iv:nYs6PwNaQBOZd6qo0wFMzxD6ObQ4FjD7CsHRjVQM9DE=,tag:hrYYXTF9JqSz5eHnN+RDSg==,type:str]
    api-key: ENC[AES256_GCM,data:CCMdpSzpjnnHRk7FPJU7D1wj8UJ0RTOgZl+RWvGodBFlwqWuXQ==,iv:nyN6KJUpGy4cYLEaJYxF0nmWS3BtKCiInJpMYMFJ/1A=,tag:zO7f4bOTrIZ8Dcu7/J+IYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ruau50zn3vvmjfw7fh2drh3l43zzr7rqxgad250clunz54xv43tqt79xw6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMm9nWTkrbUVMTE9nVWxN
            SFVGd0RXL0xOdlBjNjdYSTJQNWdQU3Y4OFdRCk11ZTZUUVAwZm1Za0M0MWZVaitI
            QUZFaGozeDJKRHg5Q0FCdHJhSWhWOEUKLS0tIHlyOG1uYWtCcTZYaUx4cG5YMmVy
            c2tnYjZqaG5pbVVxbjZiazFpT2U2QXMKJyMYYlaeshqj+ITywrjG2g6U6DHO7zJs
            ZFZyA+sspL1sWHK6d/z0qDOOrt2oruJgiVnRUEAwMJjwGaZPeuEAdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T00:07:35Z"
    mac: ENC[AES256_GCM,data:kPz/lRFKUvJjXhwNSMkqxFzuXcARd+LL9c2ofIW+cqcdSfewgFi3eiUiSBduMVHY3e+GeAj8P3hQXN6eN5iMkoYl9q1t1Uggcbh6Vco7IDa1dl1HIfh0DbLIGyUMVmf7pfaevzPXCl5rM34dMRkuTUeTvv+gAEoPbhalKsPH1Ac=,iv:dYZIQr6kcjsZgMxisrpAKXf0te0Q3CRu1bP6h9aFoNQ=,tag:j8BJvct7egxwfhhbgEE9ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
