---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Vancouver"
  KUBE_VIP_ADDR: "10.69.91.2"
  METALLB_LB_RANGE: "10.69.91.100-10.69.91.110"
  METALLB_K8S_GATEWAY_ADDR: "10.69.91.100"
  METALLB_INGRESS_ADDR: "10.69.91.101"
